name: Build 11ty

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Build with 11ty
      - name: Build 11ty
        uses: mcfitzgerald/action-build-eleventy@2.01
        with:
          path: $GITHUB_WORKSPACE
