name: Build site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repo under $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install deps
      - name: Install deps
        uses: bahmutov/npm-install@v1
      
      # Build with 11ty
      - name: Build 11ty
        uses: mcfitzgerald/action-build-eleventy@2.01
        with:
          path: $GITHUB_WORKSPACE

      # Deploy to OVH over FTP
      - name: Deploy to OVH
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: $GITHUB_WORKSPACE/_site/
          server-dir: ${{ secrets.ftp_dir }}