name: Build site

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out the repo under $GITHUB_WORKSPACE
      - name: Checkout repo
        uses: actions/checkout@v2

      # Install deps
      - name: Install deps
        uses: bahmutov/npm-install@v1
      
      # Build with 11ty
      - name: Run the build script
        run: npm run build

      # Deploy over FTP
      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: _site/
          server-dir: ${{ secrets.ftp_dir }}